bugfix: command sign -nest -t[s], must timestamped new (created) sign…
mtrojnar/osslsigncode pull request #266
Opened 2023-05-01 10:48 UTC by yjh-styx

…ature, nor current (first in chain)!

2023-05-03 10:19 UTC, mtrojnar commented
LGTM.
@olszomal Could you also take a look?

2023-05-12 10:28 UTC, olszomal requested changes

2023-05-12 10:28 UTC, olszomal commented on msi.c
> +        return p7;
```suggestion
   return p7;
```

2023-05-12 10:42 UTC, olszomal commented
It looks good to me. Fixed bug with nesting timestamped signatures.
Thank you for your contribution.

2023-05-14 18:38 UTC, mtrojnar commented
@yjh-styx Will you fix the indentation?

2023-05-14 20:32 UTC, merged