squash gcc debugger warnings
mtrojnar/osslsigncode pull request #286
Opened 2023-08-29 06:15 UTC by olszomal

2023-08-31 10:24 UTC, mtrojnar requested changes

2023-08-31 10:31 UTC, olszomal commented on pe.c
>      if (nsections == 0 || nsections > UINT16_MAX) {
Coverity scan reported untrusted loop bound in this loop:
for (i=0; i<nsections; i++)

2023-08-31 10:41 UTC, mtrojnar commented on pe.c
>      if (nsections == 0 || nsections > UINT16_MAX) {
In this case, it's the incorrect Coverity warning that should be squashed here rather than the correct GCC warning.

2023-09-05 09:40 UTC, olszomal commented
I want to check Coverity Scan behavior.

2023-09-08 09:50 UTC, mtrojnar approved these changes

2023-09-08 09:51 UTC, merged